---
- name: Establish install location.
  set_fact:
    oh_my_zsh_install_path: "/{{ zsh_user_home_dir }}/{{ zsh_user.name }}/{{ oh_my_zsh_install_directory }}"

- name: Clone Oh My ZSH repo for user.
  git:
    repo: "{{ oh_my_zsh_git_repository }}"
    dest: "{{ oh_my_zsh_install_path }}"
    update: true
    accept_hostkey: true
    version: "master"
  register: oh_my_zsh_clone

- name: Set ownership on newly cloned repository.
  file:
    path: "{{ oh_my_zsh_install_path }}"
    owner: "{{ zsh_user.name }}"
