---
- name: Derive user .zshrc path.
  set_fact:
    zsh_user_zshrc_path: "/{{ zsh_user_home_dir }}/{{ zsh_user.name }}/.zshrc"

- name: Template .zshrc into place if required.
  template:
    src: "{{ oh_my_zsh_zshrc_template }}"
    dest: "{{ zsh_user_zshrc_path }}"
    owner: "{{ zsh_user.name }}"
    mode: "0644"
    backup: "{{ oh_my_zsh_zshrc_backup }}"
  when: oh_my_zsh_zshrc_create
