---
# Note that we assume this file exists! lineinfile will fail if the file is
# not present.
- name: Export vars to .zshrc if required.
  blockinfile:
    dest: "{{ zsh_user_zshrc_path }}"
    block: "{{ zsh_user.settings }}"
    backup: "{{ oh_my_zsh_zshrc_backup }}"
  when:
    - zsh_user.settings is defined
    - zsh_user.settings|length > 0
    - not oh_my_zsh_zshrc_create
