---
- name: Establish home directory.
  set_fact:
    zsh_user_home_dir: "{{ (ansible_system == 'Darwin') | ternary('Users', 'home') }}"

- name: Ensure zsh is installed.
  block:
    - name: Install zsh for Linux.
      package:
        name: "zsh"
        state: present
      when: ansible_system == "Linux" and install_zsh

    - name: Install zsh for macOS.
      homebrew:
        name: "zsh"
        state: present
      when: ansible_system == "Darwin" and install_zsh

- name: Get zsh installed path.
  command: "which zsh"
  register: zsh_installed_path
  changed_when: false

- name: Set user shell to zsh.
  user:
    name: "{{ zsh_user.name }}"
    shell: "{{ zsh_installed_path.stdout }}"
